name: pytest

# Only one main branch, hence on all push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: Dovyski/setup-opencv-action@v1
        with:
          opencv-version: '4.0.0'

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: | 
          pipenv install --dev
          sudo apt-get install libhdf5-dev libhdf5-serial-dev libhdf5-100
          sudo apt-get install libqtgui4 libqtwebkit4 libqt4-test python3-pyqt5
          sudo apt-get install libatlas-base-dev
          sudo apt-get install libjasper-dev

      - name: Run pytest
        run: pipenv run pytest