name: Unit Test

on:  
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r ./requirements.txt

      - name: Run pytest
        run: |
          coverage run --source=ocr -m pytest ./tests/test_unit.py > unit_test.txt
          coverage html

      - name: Upload pytest log
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-log
          path: unit_test.txt

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-coverage
          path: htmlcov